### ISSUE TITLE
Add a set of commands to manage service brokers, and services

### ISSUE THREAD

**Issue by andreas-kupries** [SUSE/carrier#104]
Give a carrier instance knowledge of service brokers it can use to manage services.

Users operations should be:
  - Add service broker
  - Remove service broker
  - List brokers
  - Create service (through a broker)
  - Remove service
  - List services

Note: If a brokers are capable of listing the services currently create through them then carrier does not need a local list of services, it can simply ask the brokers it knows about.

This depends on the underlying API used to converse with browsers.

See OSBAPI (Open Service Broker API).

See also #90

**Comment by thardeck** [comment]
This issue is obsolete because it is out of date and services are implemented already as part of more fine grained cards.
