### ISSUE TITLE
One Carrier per cluster?

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#105]
We should better decide if we ever want to support multiple Carrier instances installed on the same cluster early. The decision will probably affect various other decisions (e.g. whether we need to know which carrier on the cluster we are talking to, caching carrier information like gitea urls etc).

Let's use this issue to comment on the matter.

**Comment by kkaempf** [comment]
I'd guess the underlying question was the one raised last week: Should Carrier support multi-tenancy ?

**Comment by jimmykarily** [comment]
This one is about multiple Carrier tenants on the same kubernetes cluster. There is also the multiple user tenants on the same Carrier instance which is something we most likely have to support.

**Comment by jimmykarily** [comment]
Carrier's role is to be an easier way to use your cluster not to be a completely separate entity. Carrier shouldn't create any new concepts on your cluster or new ways to separate workloads on your cluster other than the well known kubernetes concepts like namespaces.

In other words, it should always be 1 cluster <-> 1 Carrier instance.
