### ISSUE TITLE
EventListener not found error

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#108]
In some cases, after installing Carrier, when pushing the sample app, it's stuck on waiting for staging to happen (and eventually times out).

Looking at the `el-staging-listener-xxxx` pod with this command:

```
kubectl  logs -f -n eirini-workloads el-staging-listener-74654f778c-lmsw8
```

there is an error:

```
{"level":"error","ts":"2021-02-03T08:29:16.553Z","logger":"eventlistener","caller":"sink/sink.go:80","msg":"Error getting EventListener staging-listener in Namespace eirini-workloads: eventlistener.triggers.tekton.dev \"staging-listener\" not found","knative.dev/controller":"eventlistener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"80","function":"github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent"},"stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:80\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2417\nnet/http.(*timeoutHandler).ServeHTTP.func1\n\tnet/http/server.go:3272"}
```

This doesn't always happen and it's not 100% sure that it's not a red herring.

Checking manually shows that the eventlisteners is there:

```
dimitris@dk-summit-demo-ssd:~$ kubectl  get eventlistener.triggers.tekton.dev --all-namespaces
NAMESPACE          NAME               ADDRESS                                                              AVAILABLE   REASON
eirini-workloads   staging-listener   http://el-staging-listener.eirini-workloads.svc.cluster.local:8080   True        MinimumReplicasAvailable
```

(maybe wasn't `Available` at that time?).

It doesn't happen always and it's not clear what causes it. It seems like some kind of race condition. If you kill the el-staging-listener pod and try to push the app again it usually deploys fine though listing apps failed once after trying this workaround (relevant?)

**Comment by jimmykarily** [comment]
This is the response Gitea webhook got:

![image](https://user-images.githubusercontent.com/2794419/106777863-0c9c8a80-664e-11eb-8a99-c82120fa914d.png)

**Comment by andreas-kupries** [comment]
In the testing of #107 for #100 I saw that the install (including org creation and targeting) completed while the `el-staging-listener` pod was still spooling up (initialized, running, but not yet all of its containers active, i.e. it was x/y, x < y). Should maybe wait for `n/n` instead of just running.
