### ISSUE TITLE
Remove Eirini?

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#109]
Right now Eirini is only used in order to create a Statefulset out of an LRP. We don't use any other functionality from Eirini.

We should consider removing Eirini because:

- LRP is a CloudFoundry thing. Not known to anyone outside CloudFoundry
- It's equally easy to create a Deployment or Statefulset as it is to create an LRP. That means, we can directly create a Deployment instaed of an LRP
- There are other alternatives to abstract the Application concept if that's desirable (e.g. https://github.com/kubernetes-sigs/application). These tools could have bigger communities than Eirini in this world of Kubernetes.

**Comment by satadruroy** [comment]
+1 

with regards to the "Application" concept, I found it interesting that someone asked a question about multiple microservices making up an application and how carrier would deal with that. FWIW, OAM formalizes the concept of an application supporting composites via components and workloads so I wonder if we need at least some basic abstraction as well.

https://github.com/oam-dev/spec/blob/master/3.component.md

https://github.com/oam-dev/spec/blob/master/4.workload_types.md

**Comment by jimmykarily** [comment]
I've been thinking about that question. This seems to originate on [how Rio works (with riofile)](https://github.com/rancher/rio/blob/master/docs/riofile.md).

CloudFoundry, Heroku and buildpacks in general were created with a 12factor app in mind. That means, you have one app and various services your app needs. The PaaS deploys the app and gives you a way to provision the additional services. This model generally works (actually I would dare say it works in 99% of the apps out there).

Now, trying to find a case where this model doesn't work so well, we should think of an application where the services are not just external services. By external I mean services for which the developer doesn't write the code but simply wants to provision. We are talking about a microservices application on which mutliple "apps" (or "services") are developed and deployed separately and have to talk to each other.

The question is, how does the 12factor model of CloudFoundry/Heroku/buildpacks work for this case? I think, the various services of the "microservice" application are simply "apps" that are pushed on the same platform and they need to be able to talk to each other (with some additional features to not expose them to anybody else probably).

But even if this works, it still feels like a hack. The system doesn't recognize the application as one application and the features that block external access to the "microservices" are there only to support this case. This feels more like an afterthought than a real feature. On the other hand, looking at a riofile or a dockercompose or similar, the complexity of deploying your app seems to increase. Maybe so much, that using Kubernetes directly to deploy your app isn't that much harder anymore.

I haven't made up my mind yet but I tend to think that, either you have one of the 99% of the applications out there, where the  12factor  model is a good fit (one app, various external services needed), or you have an application with lots or microservices (which you develop) and in that case, you could as well deploy them on Kubernetes yourself. If you can manage the complexity of developing and deploying a microservice application with zero downtime, rollbacks and all, doing that on Kubernetes is likely the easiest of the tasks.

**Comment by jimmykarily** [comment]
A nice example of how others conceive this difference between a "traditional" 12factor app and microservices: https://www.nginx.com/blog/microservices-reference-architecture-nginx-twelve-factor-app/

**Comment by mattfarina** [comment]
I have a handful of thoughts on all of this. They are not conclusions but rather thoughts to add to the mix...

- [Cloud foundry lets you deploy multiple apps with one manifest](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-apps). I wonder both the reason for this and how popular it has been. That might help provide some insight to this discussion.
- Many years ago, I deployed apps in CF that talked with each other. All the apps were public and we passed configuration around using environment variables. This worked but was not ideal. It would have been nice for some services to remain internal and not be publicly exposed. Environment variables were a good way to tell one app which other app to use and make it easily configurable with the variety of config we could have for other apps.
- I am unsure of OAM. While I have a lot of respect for the original developer who kicked it off, I have yet to see OAM become a success. What problem does it solve for which types of end users and how does it work in a way they want to use it? I can't answer that in practice.
- I'm listed as a maintainer on https://github.com/kubernetes-sigs/application and was part of the conversations that created it. If you want to talk about using this or even features needed to fit our case, I would be happy to talk.
- I could see a more lightweight system handing the Deployment/StatefulSet. I wonder if this would be a place to have the ability to export the app as a helm chart that could be run elsewhere.

**Comment by satadruroy** [comment]
"I could see a more lightweight system handing the Deployment/StatefulSet. I wonder if this would be a place to have the ability to export the app as a helm chart that could be run elsewhere."

 A big +1 on this. Not to hijack this thread for something unrelated to Eirini (we should discuss this in a separate ticket/channel and @jandubois and @colstrom have lot of thoughts on this as well) but I am still not totally sure about this pitch for a "mini-PaaS". If instead, we can focus on carrier as another tool in the dev k8s tool chain that leverages buildpacks and stacks to generate helm charts (less ideally, kube manifests) from raw code then we can get out of the  way and let the ops folks deal however they want to with all the production deployment aspects using standard k8s stuff they should be well familiar with. Why do we need yet another "platform" on top of k8s?  That way, we play nice with whatever workflow the devs have, not have to `push` apps to production (I know it has worked well for CF but do we still need that in a k8s setup?) - I also remember Darren mentioning that one of the challenges they had with Rio was the tool was not received super favourably in the ops world because, well, they had to deal with yet another tool in a heavily regimented environment. Carrier as a tool could also have some nice follow-on synergy from RD and fit well into that chain.

As for OAM, I'm not pushing it at all - I am uncomfortable with all the formalism/ceremony around the specs before actually proving if the idea works...I just found it interesting that they have this abstraction for workloads and components but in that same vein, it also brings back for me bad memories of erstwhile "distributed computing standards" like Service Component Architecture and all that stuff...

**Comment by jimmykarily** [comment]
Lots of useful input on this Issue, thank you all! It seems that no one objects in removing Eirini and we have many other options if we want to abstract the Application concept. I'll keep this issue open until we remove Eirini and we can use the comments above as a starting point to decide what (and if) we introduce an abstraction for applications, whether we support microservices in the CF or other way and even the alternative approach of a "helm chart generator for apps" for Carrier.

**Comment by troytop** [comment]
I have no objection to removing Eirini if the default behavior of `carrier push` of an app exposing a web interface stays consistent with what cf and heroku users expect: the web service is exposed on an external URL. 

There's definitely room for other non-web applications or microservices which are not exposed externally, but we still need to expose a simplified way for users to specify internal routing (maybe just using internal hostnames and kubernetes services). 

Here's how Heroku does this:
https://devcenter.heroku.com/articles/dyno-dns-service-discovery

This is one way CF exposes apps to each other on internal interfaces:
https://github.com/cloudfoundry/cf-networking-release/blob/develop/docs/app-sd.md#internal-domains

We don't have to implement exactly the same thing, but we _should_ provide the same user functionality.

**Comment by rohitsakala** [comment]
Difference between StatefulSet and Deployment ?

- In a deployment, we can rollback to previous versions unlike in a statefulset.
- A failed deployment can be updated to make it a success in deployment unlike in a statefulset [0]

**Comment by rohitsakala** [comment]
Difference between StatefulSet and Deployment ?

- In a deployment, we can roll back to previous versions unlike in a statefulset.
- A failed deployment can be updated to make it a success unlike in a statefulset [0]. You have to update the statefulset and delete the failed pods for the statefulset to be a success.
- A statefulset maintains an identity for each pod in the replicas unlike in a deployment.
- When `volume claim templates` is defined, each statefulset pod has a volume attached to it. We cannot define `volume claim templates` in a deployment [1].
- Statefulset pod deletion, creation are done in an ordered manner. 

A deployment makes sense for our use case as statefulset is used for apps where each pod needs a unique identity and where each pod needs to store some persisted data at some file path and these are not required for our apps. Carrier uses services for persisted data. 

[0] https://github.com/kubernetes/kubernetes/issues/67250
[1] https://github.com/kubernetes/kubernetes/issues/93019

Note - This is already implemented. Writing this down so we know why we choose deployment over statefulset.
