### ISSUE TITLE
carrier apps errors listing apps

### ISSUE THREAD

**Issue by abonillabeeche** [SUSE/carrier#113]
tag 0.0.1

A previous app build failed...

🕞  [STAGE] step-create   Executing build process 
🕞  [STAGE] step-create     Installing MRI 2.7.2 ..
🕞  [STAGE] step-create       Completed in 2.425s 
🕞  [STAGE] step-create  
🕞  [STAGE] step-create   Configuring environment 
🕞  [STAGE] step-create     GEM_PATH -> "/home/cnb/.gem/ruby/2.7.0:/layers/paketo-buildpacks_mri/mri/lib/ruby/gems/2.7.0" 
🕞  [STAGE] step-create  
🕞  [STAGE] step-create Paketo Bundler Buildpack 0.0.153 
🕞  [STAGE] step-create   Resolving Bundler version 
🕞  [STAGE] step-create     Candidate version sources (in priority order): 
🕞  [STAGE] step-create       Gemfile.lock -> "2.1.1" 
🕞  [STAGE] step-create       <unknown>    -> "*" 
🕞  [STAGE] step-create       <unknown>    -> "*" 
🕞  [STAGE] step-create  
🕞  [STAGE] step-create  
🕞  [STAGE] step-create failed to satisfy "bundler" dependency version constraint "2.1.1": no compatible versions 
🕞  [STAGE] step-create ERROR: failed to build: exit status 1 .
🕞  [STAGE] step-image-digest-exporter-4ct8v 2021/01/29 18:17:53 Skipping step because a previous step failed .......^C
acepc-1:~/cf-example-sinatra #

I left an an hour later I tried to list the apps

acepc-1:~/samples/nginx # ~/carrier-linux-amd64 apps
W0129 18:49:18.333694   29636 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

🚢 Listing applications
Organization: workspace
error listing apps: failed to get routes for app 'dora': failed to list ingresses: ingresses.networking.k8s.io "dora" not found

The delete never really showed me confidence that it was deleted because of the error below...

acepc-1:~/samples/nginx # ~/carrier-linux-amd64 delete dora
W0129 18:49:31.926946   29829 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

🚢 Deleting application...
Name: dora

Deleted app code repository.
error deleting app: failed to delete eirini lrp: lrps.eirini.cloudfoundry.org "dora" not found

^^^

but I moved on and I deleted another app that was in the same boat...

acepc-1:~/samples/nginx # ~/carrier-linux-amd64 apps
W0129 18:49:39.694891   29991 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

🚢 Listing applications
Organization: workspace
error listing apps: failed to get routes for app 'sinatra': failed to list ingresses: ingresses.networking.k8s.io "sinatra" not found
acepc-1:~/samples/nginx # ~/carrier-linux-amd64 delete sinatra
W0129 18:49:46.263321   30057 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

🚢 Deleting application...
Name: sinatra

Deleted app code repository.
error deleting app: failed to delete eirini lrp: lrps.eirini.cloudfoundry.org "sinatra" not found

*again* it didn't really show that it deleted the app, but the code repo which makes sense but wasn't clear...

Finally once the trouble ones were deleted...

acepc-1:~/samples/nginx # ~/carrier-linux-amd64 apps
W0129 18:49:51.984653   30104 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

🚢 Listing applications
Organization: workspace

✔️  Carrier Applications:
|    NAME     | STATUS |                  ROUTES                   |
|-------------|--------|-------------------------------------------|
| dizzylizard | 0/1    | dizzylizard.10.0.0.161.omg.howdoi.website |
| nginx       | 1/1    | nginx.10.0.0.161.omg.howdoi.website       |

I was then able to list the apps.

**Comment by jimmykarily** [comment]
This has been fixed here: https://github.com/SUSE/carrier/pull/161 . @abonillabeeche thanks for reporting. If you encounter this on a newer version (current is v0.0.7) please re-open this or open a new issue.
