### ISSUE TITLE
Stub eirini-ingress image version

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#116]
We [are currently using the latest](https://github.com/SUSE/carrier/blob/main/cli/embedded-files/eirini/routing.yaml#L83) tag of the eirini-ingress image. We should stub it to a specific version to avoid surprises if a new image is built which is incompatible with our code.

**Comment by jimmykarily** [comment]
@mudler the images have no tags: https://quay.io/repository/mudler/eirinix-ingress?tab=tags . Can we get tags? We could use the sha256 instead if that's hard to do.

**Comment by mudler** [comment]
Should be doable, having a look :+1:

**Comment by mudler** [comment]
`quay.io/mudler/eirinix-ingress:v0.1` should be there. From now on each commit on eirini-ingress master (untagged) gets a image with the `${commit_info.short_sha}` tag, while tags starting with `v` gets the corresponding image.

**Comment by jimmykarily** [comment]
Awesome! Thank you @mudler for the fast resolution.
