### ISSUE TITLE
carrier push with no user.name and user.email configured in git

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#12]
When running `carrier push` but you don't have a user.email and user.name globally set for git you get an error:

```
From http://gitea.172.19.0.2.nip.io/dev/dizzy
 * [new branch]      main       -> carrier/main
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: no email was given and auto-detection is disabled
error: src refspec master does not match any
```

Carrier should assume any specific git configuration on the user's machine.

NOTE: If cf cli is supposed to do the pushing from here on, then we can close this issue.

**Comment by andreas-kupries** [comment]
We committed fully to the go-based cli.

**Comment by andreas-kupries** [comment]
Wait, I may have been too fast ... This said `cf cli`, no `cli`, carrier/go.

@jimmykarily Will/Could this be(come) an issue in the carrier/go also ? If yes, please re-open.

**Comment by jimmykarily** [comment]
I'm not sure how the code will be uploaded in the future. For this first version I assume we will be calling and external `git` binary (?). @viovanov was planning to work on this part of the cli. I external `git` is called then this could still be an issue.
