### ISSUE TITLE
Where should I be to push?

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#120]
From the feedback we got so far, when the time comes to push an app, the users seem to get confused on where they should be when calling `carrier push myapp`.

Probably because of previous experience with other PaaS/clis they sometimes expect it to work by specifying some command line argument or other way.

We do explain how it works in the command's help but in any case, to avoid pushing things that are not the application code we could add an confirmation before pushing the application code. To stick to the "one command to deploy" scheme we could have a timer as in:

- user calls `carrier push myapp`
- A message is shown:
  `Carrier will now deploy the application in the current directory (/home/myuser/myapp) using the name "myapp". Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)`
- The deployment continues after 5 seconds or after the user hits Enter. Deployment is aborted if Ctrl+C is hit.

If you can think of a better flow, please comment.

**Comment by andreas-kupries** [comment]
See #132
