### ISSUE TITLE
Use a smaller image for quarks secret

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#129]
Right now the image used for quarks secret is based on the kubecf stemcell. We have no need for that stemcell and the quarks secrets is just a go binary. It could even run on a "FROM scratch" image which would make the image very small. We should either create a pipeline for generate that image in our CI or do that in the quarks CI.
In any case, the quarks helm chart will need to be patched (or provide some value in values.yaml to be able to use the small image).

**Comment by andreas-kupries** [comment]
:warning: __Attention__

The docker file uses `go 1.14.7`. The local go installation has to match that, or maybe a higher version of `1.14`.
A pre-1.14 version will generate a vendor directory and module information the 1.14 will not understand and fail on.

Further ... The base image has to supply at least `groupadd` and `useradd` as admin commands. These are run by the dockerfile as part of setting up the qs binary.

The `busybox` does not have these.

**Comment by andreas-kupries** [comment]
Removed user/group operations, user definition, and use of the [tini](https://software.opensuse.org/package/tini).

The modified Dockerfile is

```
ARG BASE_IMAGE=busybox

FROM golang:1.14.7 AS build
ARG GOPROXY
ENV GOPROXY $GOPROXY

WORKDIR /go/src/code.cloudfoundry.org/quarks-secret

# Copy the rest of the source code and build
COPY . .
RUN [ -f tools/quarks-utils/bin/include/versioning ] || \
    bin/tools
RUN bin/build && \
    cp -p binaries/quarks-secret /usr/local/bin/quarks-secret

FROM $BASE_IMAGE
LABEL org.opencontainers.image.source https://github.com/cloudfoundry-incubator/quarks-secret
COPY --from=build /usr/local/bin/quarks-secret /usr/local/bin/quarks-secret
ENTRYPOINT ["/usr/local/bin/quarks-secret"]
```

While this fails when trying to run it directly via `docker run ...`, with error

```
2021-02-18T13:48:33.677Z	INFO	cmd/kubeconfig.go:16	 does not exist, using default kube config
2021-02-18T13:48:33.677Z	INFO	cmd/kubeconfig.go:20	Checking kube config
2021/02/18 13:48:34 quarks-secret command failed. : Couldn't check Kubeconfig. Ensure kubeconfig is correct to continue.: invalid kube config: Get "http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
```

I suspect, for now, that this is just an issue with trying to use it outside of a proper k8s environment, as k8s will set up for pods and their containers.

**Comment by andreas-kupries** [comment]
Hi @jandubois . Troy asked me to ping you on this one for tips and tricks you have used to make images smaller (Rancher desktop ?)

**Comment by jandubois** [comment]
@andreas-kupries I think you are already good by building `FROM scratch`. I assume you are building `FROM busybox` for debugging reasons.

My work was related to creating a minimal image that can run k3s, which really just needs the k3s binary itself, a set of root CA certs so it can pull from Dockerhub, a symlink to `/bin/sh`, and a `/tmp` directory. But that has nothing to do with your situation.

**Comment by andreas-kupries** [comment]
@jandubois Ok. Thanks for the insights. ... Yes, I should try `FROM scratch` as well. ... Oh, and good night too you, sleep well.

**Comment by andreas-kupries** [comment]
Sizes
```
quarks-secret-scratch    v0.0.754-g8ad30f7   11163558f712    52.5MB
quarks-secret-busybox    v0.0.754-g8ad30f7   07d0be9f4e54    53.7MB
quarks-secret            v0.0.754-g8ad30f7   da0392800a36    273MB
```

Does the following make sense ? (For testing the reduced image).

# Inject a modified quarks into carrier for debugging

  1. Create a local web server on some port, capable of delivering static files.
  2. Edit `deployments/quarks.go:25:quarksChartURL` to reference a custom tar ball on that server.
  3. Rebuild `carrier`.
  4. Take the original qs tarball from the original `quarksChartURL`
       1. Unpack it.
       2. Edit the `quarks-secret/values.yaml` file, specifically the keys `image.tag`, `image.org`, and `image.repository` (See lines 15ff or so). Make them reference a personal docker image somewhere (for example under a personal account on docker hub).
  5. Repackage the edited chart into a tarball and place it into the root directory of the web server started in step 1. Use the same name as was used in step 2.
  6. Go the sources of the modified quarks-secret, and
       1. Create a new docker image for it (`docker build .`), then
       2. Tag and push that image to the location used in step 4.2.

At this point, when the rebuild `carrier` invokes `install` it should:

  1. Pull the custom tarball from the local webserver, then
  2. Install the custom chart with the custom docker image location, which then
  3. Pulls the custom docker image containing the modified qs binary.

**Comment by andreas-kupries** [comment]
Results:
  1. The injection procedure above works.
  2. An stumbling point was my registry proxy. I had forgotten that with the proxy running you cannot push to docker hub. It was necessary to disable it to get the modified qs images up.
  3. All possibilities (unmodified base, busybox, and from scratch) work, i.e. deploy the qs pod just fine, with nominal output in the logs.

Things to think about now:

  - Coordination with upstream to see if we can make the reduced qs image the official/default build.
  - Ditto for getting an official chart using that image.
  - See also #151 for other possibilities (Move the chart into the carrier binary, add templating to redirect the image location, ...)

**Comment by andreas-kupries** [comment]
Forgotten to say, confirmed with `k describe pod` that the proper modified image was pulled.
With the `qs:scratch` also tried pushing an app. Worked as well.
Now running the :cat2: for it.

**Comment by andreas-kupries** [comment]
:cat2: works

**Comment by jimmykarily** [comment]
Follow up : #158
