### ISSUE TITLE
`carrier delete` does sometimes exit before the deletion is finished

### ISSUE THREAD

**Issue by thardeck** [SUSE/carrier#131]
While writing the acceptance tests it occurred that `carrier apps` still listed the deleted app after `carrier delete` exited successfully.

Since this can result in race conditions we should make sure that `carrier` does not exit before the app and everything related to it was successfully deleted.

**Comment by agracey** [comment]
This might be nice to have both options available. If it's not any extra future maintenance, it might be worth having a flag that allows for a quick exit while the default waits?
