### ISSUE TITLE
`carrier install` installs wiremock (test) component or eirini

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#14]
The testing directory should be skipped when installing Eirini with flat yaml files:

https://github.com/cloudfoundry-incubator/eirini-release/tree/master/deploy/testing

Wiremock is only used in tests (in Eirini project) to mock Cloud Controller requests. This has no place in production deployments. Consider opening an issue in the eirini-release repo although those flat yamls are meant to be used as a guide on how to deploy Eirini rather than ready-to-install solution.

**Comment by andreas-kupries** [comment]
Revalidate when the cli installs eirini.

**Comment by jimmykarily** [comment]
The go based installer no longer installs wiremock: https://github.com/SUSE/carrier/blob/main/cli/deployments/eirini.go#L131
