### ISSUE TITLE
Allow Acceptance tests to run in multiple ginkgo nodes

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#142]
Currently the currently targeted org is always looked up in the config file in the home directory of the user. Although we use a different cluster per ginkgo node, they both use that file to refer to the targeted org. This results in flaky tests (e.g. https://github.com/SUSE/carrier/blob/main/acceptance/apps_test.go#L14) because the test may target an org but the other ginkgo node may target another in the meantime so when the first test tries to list the deployed apps, it lists those of the org of the other ginkgo node. 

This may not be a problem for the developer since they will probably use only one carrier instance per machine per user but it is a problem for tests. 

One solution would be to be able to override the default config location with a command line arg or an environment variable.

After fixing this, we should revert back to using more ginkgo nodes (https://github.com/SUSE/carrier/pull/137/commits/cf01b573a601beb0fa1c6aaa727814f0fa1df22d).

- [x] Environment variable for config directory.
- [x] Global cli option for the same.
- :warning: Check for ordering issues with the backend clients and their usage of config.
- [x] Document location of configuration, and how to influence it.
- [x] Change :cat2: to use the above to place config into node-specific directories
- [x] Change :cat2:  back to use of 2 ginkgo nodes

**Comment by andreas-kupries** [comment]
- We already have a global option `--config-file` (possibly since Vlad's work was added).
  - There is no associated environment variable.
