### ISSUE TITLE
Deploy wordpress (no db)

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#144]
We need to check if the PHP buildpack we are using is capable of running Wordpress. This story doesn't include the setup of Wordpress which comes after deployment.

**Comment by jimmykarily** [comment]
I can't get Wordpress to run and while debugging things I fell on this one: https://github.com/paketo-buildpacks/feedback/discussions/2#discussioncomment-293868 (wordpress is in the list of things for 2021). Maybe it can still run with the PHP buildpack though. Will keep trying.

**Comment by jimmykarily** [comment]
I got things working with this buildpack.yml

```
---
php:
  script: index.php
  webserver: nginx
  webdirectory: htdocs
```
(I put the extracted wordpress directory in an `htdocs` directory at the root of the app directory next to the buildpack.yml).
I now get this error:

```
 Call to undefined function gzinflate() in /workspace/source/app/htdocs/wp-includes/class-requests.php:949
```

It seems that this should be set to "On": https://github.com/paketo-buildpacks/php-web/blob/main/config/php-ini.go#L288
but it is not templetized.

**Comment by jimmykarily** [comment]
Created an issue here: https://github.com/paketo-buildpacks/php-web/issues/124
In the meantime looking for a workaround. Currently trying to build a custom builder with a modified PHP buildpack to see if we face more issues, other than zlib compression.

**Comment by jimmykarily** [comment]
It could be that the php-dist buildpack is missing something here: https://github.com/paketo-buildpacks/php-dist/blob/main/buildpack.toml#L96

Mixins concept: https://buildpacks.io/docs/concepts/components/stack/#mixins

**Comment by jimmykarily** [comment]
Additional data: the dependencies for the buildpacks are shared with the old (non cnb) buildpacks:
e.g. https://github.com/paketo-buildpacks/mri/blob/main/buildpack.toml#L41

(more here: https://buildpacks.cloudfoundry.org/#/dependencies)


The --with-zlib=shared must be coming from how those dependencies are used in CloudFoundry. With that in mind, this issue has some useful info on how the paths work: https://github.com/cloudfoundry/php-buildpack/issues/5

**Comment by jimmykarily** [comment]
This is what "shared" means: https://github.com/php/php-src/blob/master/configure.ac#L990

**Comment by jimmykarily** [comment]
Found a workaround: https://github.com/paketo-buildpacks/php-web/issues/124#issuecomment-779860436

**Comment by jimmykarily** [comment]
Created PR: https://github.com/paketo-buildpacks/php-web/pull/125

**Comment by jimmykarily** [comment]
There is already a way to enable zlib: https://github.com/paketo-buildpacks/php-web/issues/124#issuecomment-779919936

I tested it and this works:

```
~/workspace/carrier/assets/wordpress (wordpress)*$ cat .php.ini.d/extensions.ini
extension=zlib
```

**Comment by jimmykarily** [comment]
For reference this is how I setup the application directory:

```
~/workspace/carrier/assets/wordpress (wordpress)*$ ls -la
total 8
drwxr-xr-x 4 opensuse users   59 Feb 17 06:55 .
drwxr-xr-x 4 opensuse users   49 Feb 16 10:32 ..
-rw-r--r-- 1 opensuse users   88 Feb 16 14:26 buildpack.yml
drwxr-xr-x 5 opensuse users 4096 Feb 16 10:32 htdocs
drwxr-xr-x 2 opensuse users   28 Feb 17 06:55 .php.ini.d
~/workspace/carrier/assets/wordpress (wordpress)*$ cat buildpack.yml 
---
php:
  version: 7.3.x
  script: index.php
  webserver: nginx
  webdirectory: htdocs
~/workspace/carrier/assets/wordpress (wordpress)*$ cat .php.ini.d/extensions.ini 
extension=zlib
```

the htdocs directory is simply the extracted Wordpress tarball. `carrier push wordpress` and enjoy!

**Comment by jimmykarily** [comment]
Also:
- enabled mysqli extension by adding `extension=mysqli` to the `extensions.ini` file mentioned above.
-  created a mysql database using this helm chart: https://bitnami.com/stack/mysql/helm
and pointed wordpress wizard to it (I had to create the database manually by shelling out to the mysql pod).

Wordpress installed just find after that:

![image](https://user-images.githubusercontent.com/2794419/108173304-a7916c00-7106-11eb-9d3b-54a9719708fc.png)

**Comment by kkaempf** [comment]
Awesome work !

Time to think about what to demo next week :wink:

**Comment by kkaempf** [comment]
Can we make a testcase out of this ? :thinking:
