### ISSUE TITLE
Carrier Acceptance Tests

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#15]
We need a test suite we can run to be sure we didn't break any existing functionality.

Maybe it's too early but better start early than having to backfill the suite with tests later.

# Acceptance Criteria

- It should be possible to parallelize (each instance uses it's own cluster ? cluster pool ?)
- Should be possible to run in GitHub actions
- The test suite should complete in <= 10 minutes (and stay this way, either by parallelizing more or making the suite faster)
- For now it should check the basic functionality: (installation, application pushing, uninstallation etc)

Some tests could assume Carrier is running (e.g. tests that push apps) but some others can't (e.g. the tests that check install/uninstall). These 2 groups may not be able to run parallelized, sharing the same cluster. Needs some thought.

**Comment by andreas-kupries** [comment]
Fixed by #135
