### ISSUE TITLE
Use Kubernetes common labels for Carrier objects

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#150]
We are using custom labels to identify Carrier objects (e.g. here: https://github.com/SUSE/carrier/blob/main/paas/client.go#L485-L487)

There is some good reasoning on why standard labels are better in this page: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

Doing this will help us identify and group objects that belong or where deployed by Carrier. This can also happen in some Web UI in the far future.

**Comment by rohitsakala** [comment]
A new issue is created for the remaining work to be done. #218.
