### ISSUE TITLE
carrier binary version not updated (always at version 0.1)

### ISSUE THREAD

**Issue by svollath** [SUSE/carrier#152]
Carrier version 0.0.1 through 0.0.3 - the binaries do alwas report version 0.1:

```
cap@jump:~/caasp4/tf1-cluster> ./carrier-linux-amd64-0.0.1 --version
carrier version 0.1
cap@jump:~/caasp4/tf1-cluster> ./carrier-linux-amd64-0.0.2 --version
carrier version 0.1
cap@jump:~/caasp4/tf1-cluster> ./carrier-linux-amd64-0.0.3 --version
carrier version 0.1
```

How to reproduce:
Download e.g. the linux binary for carrier (https://github.com/SUSE/carrier/releases/download/v0.0.3/carrier-linux-amd64) and run `carrier-linux-amd64 --version`.

Verified the 3 given binaries do actually differ, but all do report version 0.1:
```
> md5sum carrier-linux-amd64-0.0.*
5d98b161492d4739e7b6fc3998c788ae  carrier-linux-amd64-0.0.1
1560d957fff7fbe56354720a6a9039cb  carrier-linux-amd64-0.0.2
b83ea99655b29a8858da2e988d03d635  carrier-linux-amd64-0.0.3
```

**Comment by jimmykarily** [comment]
We should inject the version at build time as:

- If current commit is tagged, the tag becomes the version
-  If not, then the commit sha is used as a `dev` version (maybe combined with the previous tag or something like that)

I think we were doing something similar in kubecf, we can have a look there.
