### ISSUE TITLE
Listing apps: Any failure for an app listed, aborts listing

### ISSUE THREAD

**Issue by svollath** [SUSE/carrier#155]
Issue:
Listing apps seems to abort listing apps, if there's a failure in listing e.g. the first app - this implies we cannot list all apps, if one of them can't be listed.

How to reproduce:
- push sample apps, e.g. sample-0, and sample-1 (while currently, in my environment those apps can't be listed, due to https://github.com/SUSE/carrier/issues/154)
- run e.g. `./carrier-linux-amd64-0.0.3 apps`

Output:
```
> ./carrier-linux-amd64-0.0.3 apps
🚢 Listing applications
Organization: suse
error listing apps: failed to get routes for app 'sample-0': failed to list ingresses: the server could not find the requested resource
```

... see that app `sample-1` isn't mentioned/listed at all, while it does exist:

```
> kubectl get deployments.apps -n carrier-workloads 
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
el-staging-listener   1/1     1            1           43m
suse.sample-0         1/1     1            1           29m
suse.sample-1         1/1     1            1           24m
```

In addition there's currently no way in carrier to list a specific app -> will report that as enhancement.

**Comment by andreas-kupries** [comment]
Reproduced the issue by manually deleting the ingress resource for one of three pushed applications.
