### ISSUE TITLE
Carrier to list information on a single app specified

### ISSUE THREAD

**Issue by svollath** [SUSE/carrier#156]
Use case:
Given there is more that one app deployed to an org -
As a user, I like to get information on a single app, I do specify -
e.g. by running `carrier app sample-1`

So, e.g.:
`./carrier-linux-amd64-0.0.3 apps` does list information on "sample-0" and "sample-1" (-> all apps in the targeted org)
`./carrier-linux-amd64-0.0.3 app sample-1` would only list information on "sample-1"

while `carrier app <app-name>` could list more detailed information on a singe app, in addition.

((Related to https://github.com/SUSE/carrier/issues/155))

**Comment by andreas-kupries** [comment]
Should be fixed by #232
