### ISSUE TITLE
Users shouldn't be able to delete services when those are bound to applications

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#198]
## Acceptance Criteria

- When the user tries to delete a service but the service is bound some application, an error should be returned listing the bound applications
- The user should have a way to list the bound applications without trying to delete the Service (e.g. `carrier service mydb`)

**Comment by agracey** [comment]
How much harder would it be to prompt with a "do you want to cascade the deletion?"

**Comment by jimmykarily** [comment]
Shouldn't be harder. In any case we need to print all the bound apps so the additional question doesn't add much complexity. Just to clarify, "cascade" means, unbind from all apps and delete right?

**Comment by andreas-kupries** [comment]
When cascading I would expect to see a list of affected apps before proceeding (Same 5 second wait as for `push`).

**Comment by andreas-kupries** [comment]
Actually, I would expect to see the set of apps even when not cascading.

**Comment by jimmykarily** [comment]
Another thing, the user is able to delete an application that has a Service bound but the `ServiceBinding` it not deleted. After deleting the application there is no way to delete the `ServiceBinding` anymore because Carrier complains that the application is no longer there. Not sure if we need a new issue to fix this or it will be fixed as part of this one.
