### ISSUE TITLE
carrier cli install - Should it roll back on failure ?

### ISSUE THREAD

**Issue by andreas-kupries** [SUSE/carrier#20]
Tried to use the `cli install` in a k3d cluster I used for a bash-based carrier before. The bash carrier was deleted.
Result:
```
work@tagetarl:~/SUSE/dev/carrier> cli/dist/carrier install
Carrier installing...
[Shared] system_domain The domain you are planning to use for Carrier. Should be pointing to the traefik public IP () : 
🚢 Traefik already installed, skipping
🚢 Deploying Quarks
✔️  Quarks deployed
Couldn't install carrier: Namespace gitea present already
```

So, wondering if the `install` should roll back the pieces it has already done when it fails in some later stage.
Or, maybe have `uninstall` capable of cleaning up a partial installation ?

This all might be for post MVP.

**Comment by agracey** [comment]
From someone who dealt with a lot of CF installs: 

Rolling back automatically is not helpful as it doesn't allow for a partial install to be debugged. Having a `--force` flag or similar do a cleanup regardless of state would be my request.

**Comment by andreas-kupries** [comment]
Closing it as moot.
