### ISSUE TITLE
"carrier push" must check its arguments

### ISSUE THREAD

**Issue by kkaempf** [SUSE/carrier#206]
Running "carrier push ." (missing the name) results in
```
...
error pushing app: create repo failed: failed to create application: 422 Unprocessable Entity: {"message":"name is reserved [name: .]","url":"http://gitea.192.168.39.224.omg.howdoi.website/api/swagger"}
```

which is pretty non-intuitive.

Instead `carrier push` should check its arguments
- first argument must be name
- second argument must be (resp. expand to) a directory

and give proper error messages.

**Comment by andreas-kupries** [comment]
Duplicate of #123
