### ISSUE TITLE
Spike: Improve CI performance and stability

### ISSUE THREAD

**Issue by thardeck** [SUSE/carrier#217]
Our CI often takes quite some time to finish and runs into timeouts and other various issues.

### Potential improvements:
* warm up cluster
* more gingko nodes
* local/public cloud runners
...

## Acceptance criteria
* Findings are documented
* Issues are fixed or Github items are created
* Time box: one work week

**Comment by kkaempf** [comment]
The `safe to test` label, as suggested [by github](https://securitylab.github.com/research/github-actions-preventing-pwn-requests) seems to be a good (initial) safeguard for 'external' PRs.

**Comment by kkaempf** [comment]
re-running on a "warmed up" cluster doesn't make a huge difference:
- first run ~ 15 mins
- second run ~ 14 mins
- third run ~ 13 mins

**Comment by kkaempf** [comment]
> The `safe to test` label, as suggested [by github](https://securitylab.github.com/research/github-actions-preventing-pwn-requests) seems to be a good (initial) safeguard for 'external' PRs.

Confirmed. The trigger is on 'adding event to PR', so the action runs once after the label has been set.
Subsequent edits of the PR do not re-trigger the action run. Only removal and re-adding of the label (needs repo write access) does.

**Comment by kkaempf** [comment]
By checking `

> re-running on a "warmed up" cluster doesn't make a huge difference:
> 
>     * first run ~ 15 mins
> 
>     * second run ~ 14 mins
> 
>     * third run ~ 13 mins

Adding more hardware (+50% cpu cores, +100% main memory) does not improve these numbers.

**Comment by kkaempf** [comment]
Wow, warmed cluster and 4 parallel gingko nodes - down to 8 minutes !

https://github.com/SUSE/carrier/runs/2120683393
