### ISSUE TITLE
`carrier cli option validation/entry` - Post MVP

### ISSUE THREAD

**Issue by andreas-kupries** [SUSE/carrier#22]
The `carrier install` method currently does not validate the data entered interactively for the options needed by the deployments it uses.

Post MVP.

Split off into #29:
None of these options are exposed to the command line either, i.e. currently only interactive entry is possible.
Entry via cli options is not supported, but IMHO should.
Entry via environment variables is not suported either.
Note, this might be automatically supported via cobra when they are exposed as cli options.

**Comment by andreas-kupries** [comment]
I believe this has become moot. The only install is the system domain, and that cannot be truly validated.

**Comment by jimmykarily** [comment]
True. If we introduce any other user input we will validate it no implementation so no need for this story. Closing.
