### ISSUE TITLE
Carrier assumes app branch as 'master'

### ISSUE THREAD

**Issue by kkaempf** [SUSE/carrier#243]
Doing a `carrier push` inside a checked-out copy of https://github.com/chimera-kube/chimera-controller fails with a git error:

```
> carrier push kubewarden

🚢 About to push an application with given name and sources into the specified organization
Name: kubewarden
Sources: /abuild/projects/rancher/chimera/chimera-controller
Organization: workspace

⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)

✔️  Application Repository created.

Creating webhook in the repo...

Preparing code ...

Pushing application code ...

:forbidden:App push failed
Stdout: Reinitialized existing Git repository in /tmp/carrier-app909438524/.git/
Fetching upstream
From https://github.com/chimera-kube/chimera-controller
...
error: src refspec master does not match any
error: failed to push some refs to 'http://gitea.192.168.39.96.omg.howdoi.website/workspace/kubewarden'

Stderr: 
error pushing app: failed to git push code: push script failed: exit status 1
```

**Comment by kkaempf** [comment]
Looks like Carrier has `master` hard coded [here](https://github.com/SUSE/carrier/blob/df5065e4c94cb995651e140e2e7a0bc230b8b499/internal/cli/clients/client.go#L1277)

Changing this line from
> git push carrier master:main

to
> git push carrier main:main

makes `carrier push` pass.

**Comment by agracey** [comment]
The copy into /tmp/ should exclude ./.git/ (and potentially anything in `.carrierignore`?)

**Comment by kkaempf** [comment]
> The copy into /tmp/ should exclude ./.git/ (and potentially anything in `.carrierignore`?)

:thinking: from my understanding there's no copy to /tmp but a "git init; git remote add <gitea>; git push <gitea>" !?

**Comment by jimmykarily** [comment]
There is a copy of code happening here: https://github.com/SUSE/carrier/blob/main/internal/cli/clients/client.go#L1162
and as far as I can tell it copies everything (`.git` included).

Even if we skip the `.git` directory, the global config from the user's home directory will probably be respected. I think that's where the default branch is defined (https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch). 
I think @kkaempf fix if fine for now. The pushing of the code needs some re-thinking. One of the things we may do if we decide to stick to `git push` is to use go bindings for git to get rid of the external `git` dependency. Maybe we can fix some of these problems in the process.
