### ISSUE TITLE
Ensure golang clients are always talking to the same cluster as external `kubectl`

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#40]
The golang installer is using both, external `kubectl` calls and golang kubernetes clients to do things on the cluster. The golang client [only depends on KUBECONFIG environment variable](https://github.com/SUSE/carrier/blob/main/cli/cmd/install.go#L40) while kubectl could be using a cluster targeted by `~/.kube/config`. This could result in some of our resource being installed on one cluster and some others on another.

We should make sure external `kubectl` calls point kubectl to the same cluster. The way the cli works now, this could simply mean setting the `KUBECONFIG` environment variable in the external `kubectl` invocation.

NOTE: The same thing should be happening with `helm` external invocations.

**Comment by andreas-kupries** [comment]
@rohitsakala IIRC I have seen work from you on this in your minikube branch.

**Comment by rohitsakala** [comment]
Vlad's PR has completed this issue. Vlad's PR uses code to load config that external `kubectl` command line uses. So, whenever we run carrier, the goclient will use the context that kubectl uses.

**Comment by rohitsakala** [comment]
Design

Add a global flag `kubeconfig`. If specified carrier will use this kubeconfig.
If the flag is empty, then carrier will use defaultloadingrules of `kubectl` external cli.

PR -

Tested
1. Without explicit `kubeconfig`
2. With explicit `kubeconfig`

**Comment by rohitsakala** [comment]
Design

Add a global flag `kubeconfig`. If specified carrier will use this kubeconfig.
If the flag is empty, then carrier will use defaultloadingrules of `kubectl` external cli.

PR -

Tested
1. Without explicit `kubeconfig`
2. With explicit `kubeconfig`

Depends on Vlad's PR - #43

**Comment by andreas-kupries** [comment]
More by #43
