### ISSUE TITLE
When installer times out waiting for a Pod, print the relevant events

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#53]
E.g. when dockerhub is rate limiting us, carrier installer will simply timeout but there is not way for the user to tell because the relevant events are never printed out.

The user could go and check manually on what's wrong but it would be useful to see the relevant events immediately.

It's also useful for CI (when things timeout) so we don't need to find a way to ssh to the CI container and check.

## Possible fix:

We need to run the equivalent of this command:

```
kubectl get event --namespace carrier-registry --field-selector involvedObject.name=$(kubectl get pods -o=jsonpath='{.items[0].metadata.name}'  --selector=app.kubernetes.io/name=container-registry -n carrier-registry)
```

somewhere here: https://github.com/SUSE/carrier/blob/main/cli/kubernetes/cluster.go#L213

**Comment by andreas-kupries** [comment]
FYI ... I pulled the rug out under a running `install`, and got this result:

```
🚢 Deploying Quarks...
Usage:
  carrier install [flags]

Flags:
  -h, --help                   help for install
  -c, --kubeconfig string      (KUBECONFIG) Path to a kubeconfig, not required in-cluster
  -n, --non-interactive        Whether to ask the user or not
      --system-domain string   The domain you are planning to use for Carrier. Should be pointing to the traefik public IP
  -v, --verbose                Wether to print logs to stdout (default true)

error installing Carrier: Couldn't install carrier: failed waiting Quarks cf-operator deployment to come up: Get https://0.0.0.0:37973/api/v1/namespaces/quarks/events?fieldSelector=involvedObject.name%3Dquarks-cf-operator-69b4cff448-xxdkh: dial tcp 0.0.0.0:37973: connect: connection refused: Get https://0.0.0.0:37973/api/v1/namespaces/quarks/pods/quarks-cf-operator-69b4cff448-xxdkh: dial tcp 0.0.0.0:37973: connect: connection refused
```

Note, this was unable to ask for and show events, because, well, rug pulled out (I killed the k3s).

What was interesting is that it shows the `usage` information before the error. That surprised me. might be a cobra misconfig ?

**Comment by jimmykarily** [comment]
Trying to fetch the events of a pod that isn't starting is an operation that could fail itself too, which is what happens here. I don't know why cobra decided to print the "Usage" text. We need to look at the cobra code and see what is the condition to decide to do so. I did a quick search for `Usage` on GitHub but couldn't figure it out. Need some investigation. 

It still prints a helpful message (connection refused) but the experience could be improved. Feel free to create a lower priority issue for this.

**Comment by jimmykarily** [comment]
Trying to fetch the events of a pod that isn't starting is an operation that could fail itself too, which is what happens here. I don't know why cobra decided to print the "Usage" text. We need to look at the cobra code and see what is the condition to decide to do so. I did a quick search for `Usage` on GitHub but couldn't figure it out. Need some investigation. 

It still prints a helpful message (connection refused) but the experience could be improved. Feel free to create a lower priority issue for this.

**Comment by jimmykarily** [comment]
Trying to fetch the events of a pod that isn't starting is an operation that could fail itself too, which is what happens here. I don't know why cobra decided to print the "Usage" text. We need to look at the cobra code and see what is the condition to decide to do so. I did a quick search for `Usage` on GitHub but couldn't figure it out. Need some investigation. 

It still prints a helpful message (connection refused) but the experience could be improved. Feel free to create a lower priority issue for this.

**Comment by andreas-kupries** [comment]
See #68 for the fix, as proposed by @viccuad

**Comment by jimmykarily** [comment]
#68 was merged. Shall we close this one?
