### ISSUE TITLE
Improve application staging logs

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#75]
Right now we print pod names and other information but it's not obvious to the user where the logs come from and what they refer to (e.g. "pushing code", "staging" ?)

We should limit the output to only the useful stuff.

**Comment by andreas-kupries** [comment]
First some investigation results to get my head into the log watcher/tailer used here.

  1. Staging logs generated by the tailer are currently of the form `{{color .PodColor .PodName}} {{color .ContainerColor .ContainerName}} {{.Message}}`. This is a template used to format a log entry structure. From the above each log line contains 3 pieces of information: origin pod, container in pod, message itself, with the first two additionally colorized.

  2. The only namespace monitored when pushing is `eirini-workloads` (1).

  3. The regular expression ".*%s.*" is used to set up a PodQuery, i.e. to limit the tailing to the pods related to the application in question, "%s" is the placeholder for the name. This should pick up the staging pods, and the app pod itself, and only them.

      Note: This is buggy IMHO, because if you push, for example, applications `foo` and `foobar` at the same time (in different terminals), then the tailer for `foo` looks to be picking up the pods and logs for `foobar` also.

      I suspect that we need ".*-%s-.*", i.e. note the additional dashes separating the app name in the pod name from the surrounds.

      @viovanov Can you confirm/falsify my thoughts wrt the possible bug ?

----
  1. The backend system for logging is generic enough to allow watching multiple namespaces. Push simply does not configure that.

**Comment by andreas-kupries** [comment]
Confirmed the bug wrt picking up `foo` and `foobar`, although I trialed with `sample` and `samplefoo`. The push for the shorter name prints the logs for both apps.
