### ISSUE TITLE
Add annotations needed for Ingress in gke

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#98]
This is splitting the issue described here into a different issue:

https://github.com/SUSE/carrier/pull/95#issuecomment-769865462

**Comment by jimmykarily** [comment]
I'm trying to understand how to make the configuration of traefik consistent across different clusters.
Comparing the (working) k3d which already has traefik to the (non-working) gke  where we install traefik ourselves, the versions are:

- k3d: (1.81.0 from here? https://staging.artifacthub.io/packages/helm/helm-stable/traefik/1.81.0)
```
 13   generation: 1                                                                 
 14   labels:                                                                       
 15     app: traefik                                                                
 16     app.kubernetes.io/managed-by: Helm                                          
 17     chart: traefik-1.81.0                                                       
 18     heritage: Helm                                                              
 19     release: traefik   
```
- gke:
  - helm chart: https://github.com/SUSE/carrier/blob/main/cli/deployments/traefik.go#L26
  - app version 2.3.3 (https://github.com/traefik/traefik-helm-chart/blob/v9.11.0/traefik/Chart.yaml#L6

also the k3d one is configured through a config.toml (mounted from a configmap) and the one we install (with helm) has command line arguments that configure it (on the Deployment).

**Comment by jimmykarily** [comment]
Differences between traefik v1 and v2 may explain things a bit: https://doc.traefik.io/traefik/migration/v1-to-v2/

**Comment by jimmykarily** [comment]
The 2 needed annotations for traefik v2 are documented here: https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/

**Comment by jimmykarily** [comment]
I don't see a global option in Traefik to say "use these entrypoints for all Ingresses" so as to avoid the annotations (or a similar one for tls).

We will probably have to add a flag to the eirinix extension (https://github.com/mudler/eirini-ingress) to generate ingresses with these annotations. E.g. `--ingress-annotations 'annotation1, annotation2'`. @mudler does that sound reasonable or do you think there is a better way to have annotated Ingresses created?

**Comment by jimmykarily** [comment]
Useful background:

- https://github.com/traefik/traefik/issues/6074
- https://github.com/traefik/traefik/pull/6160

**Comment by jimmykarily** [comment]
Oh it seems it's already supported: https://github.com/mudler/eirini-ingress/blob/master/cmd/internal/root.go#L108 !
Trying now.

**Comment by mudler** [comment]
> Oh it seems it's already supported: https://github.com/mudler/eirini-ingress/blob/master/cmd/internal/root.go#L108 !
> Trying now.

yup! and it's already being used here: https://github.com/SUSE/carrier/blob/b53ff7c17b66532c55a24fcb40ad1cdaf50f94a7/eirini/eirini-release/deploy/core/routing.yaml#L88

**Comment by jimmykarily** [comment]
```
│                                                                                                                                                                           │
│ Error: unknown flag: --annotations                                                                                                                                        │
│ Usage:                                                                                                                                                                    │
│   eirini-ingress [flags]                                                                                                                                                  │
│   eirini-ingress [command]                                                                                                                                                │
│ Available Commands:                                                                                                                                                       │
│   help        Help about any command                                                                                                                                      │
│   version     Print the version number                                                                                                                                    │
│ Flags:                                                                                                                                                                    │
│   -h, --help                help for eirini-ingress                                                                                                                       │
│ unknown flag: --annotations                                                                                                                                               │
│   -k, --kubeconfig string   Path to a kubeconfig, not required in-cluster                                                                                                 │
│   -l, --labels string       Label to apply to the created resources ( json form '{ 'foo': 'bar' }' )                                                                      │
│   -n, --namespace string    Namespace to watch for Eirini apps (default "eirini")                                                                                         │
│   -t, --tls                 Enable TLS support                                                                                                                            │
│ Use "eirini-ingress [command] --help" for more information about a command. 
```

older version?

**Comment by andreas-kupries** [comment]
The referenced file is, I believe the eirini from the bash-carrier.
for go we should look at https://github.com/SUSE/carrier/blob/main/cli/embedded-files/eirini/routing.yaml#L88 instead, I believe.

**Comment by andreas-kupries** [comment]
@jimmykarily Note @mudler and my comments about the routing.yaml file we have in our eirini deployments.

**Comment by jimmykarily** [comment]
@andreas-kupries that's where we got our embedded file from. `diff` shows no difference so we didn't alter it in any way.
Also: 

```
eirini-ingress-78d5465675-nx57q:/ # /bin/eirini-ingress version
Eirini Ingress Version: 0.0.1
Go Version: go1.12.17
Go OS/Arch: linux/amd64
```

and 

```
 88   containerStatuses:                                                            
 89   - containerID: containerd://24eb4f0d947bc5ef289e4726491127e9eed6f086833bf3dcdb3ec295fd3b5d1d
 90     image: quay.io/mudler/eirinix-ingress:latest                                
 91     imageID: quay.io/mudler/eirinix-ingress@sha256:637187fe65f35e211ff9e3a7be615e9ea23e97584e9de690f7955306036e14af
 92     lastState: {}                                                               

```

which makes me wonder where we got this image from.  This repo doesn't have any tags: https://github.com/mudler/eirini-ingress

**Comment by andreas-kupries** [comment]
I think/suspect that @mudler is telling us that we should edit this file to add the needed annotations, in the referenced place ?
Ettore, can you clarify ?

**Comment by mudler** [comment]
> ```
> │                                                                                                                                                                           │
> │ Error: unknown flag: --annotations                                                                                                                                        │
> │ Usage:                                                                                                                                                                    │
> │   eirini-ingress [flags]                                                                                                                                                  │
> │   eirini-ingress [command]                                                                                                                                                │
> │ Available Commands:                                                                                                                                                       │
> │   help        Help about any command                                                                                                                                      │
> │   version     Print the version number                                                                                                                                    │
> │ Flags:                                                                                                                                                                    │
> │   -h, --help                help for eirini-ingress                                                                                                                       │
> │ unknown flag: --annotations                                                                                                                                               │
> │   -k, --kubeconfig string   Path to a kubeconfig, not required in-cluster                                                                                                 │
> │   -l, --labels string       Label to apply to the created resources ( json form '{ 'foo': 'bar' }' )                                                                      │
> │   -n, --namespace string    Namespace to watch for Eirini apps (default "eirini")                                                                                         │
> │   -t, --tls                 Enable TLS support                                                                                                                            │
> │ Use "eirini-ingress [command] --help" for more information about a command. 
> ```
> 
> older version? I also tried the `ANNOTATIONS` env var but it is ignored.

looks like the image didn't get updated indeed - Dockerhub rate limit prevented quay.io to build it :( I'll try to build a new image now

@andreas-kupries : yup exactly, but indeed the correct file is the one you mentioned :+1:  I was still looking at the bash parts of it :facepalm:

**Comment by mudler** [comment]
New image should be there soon: https://quay.io/repository/mudler/eirinix-ingress?tab=info :+1: JFIY it contains also this change: https://github.com/mudler/eirini-ingress/commit/3fd1e1c831a790d50396ec3531c0e30aaaecd84d which should enable TLS to work properly (I did tried only locally at that time..)

**Comment by jimmykarily** [comment]
> I think/suspect that @mudler is telling us that we should edit this file to add the needed annotations, in the referenced place ?
> Ettore, can you clarify ?

yes that's where it will end up, I was first trying  to manually edit the eirini-ingress deployment first and see if the ingresses get the annotation. Will try with the new image.

**Comment by jimmykarily** [comment]
Latest image works! I will create  a PR now.
